### ISSUE TITLE
How to use with Laravel?

### ISSUE THREAD

**Issue by inmanturbo** [okapi-web/php-aop#25]
Hello, I see you've updated this wonderful idea to work with php `8.2`

How do I use it with laravel?

**Comment by WalterWoshid** [comment]
Hi @inmanturbo,

to use it with Laravel, you can just install it like you would usually do (more instructions in the [README.md](https://github.com/okapi-web/php-aop/blob/master/README.md) file and in the [Implicit Aspects Section](https://github.com/okapi-web/php-aop/blob/master/README.md#implicit-aspects) or the Explicit Aspects Section if you want to add custom Aspects to your own classes)

1. Install the package: `composer require okapi/aop`
2. Create the `Kernel.php` file in your new `app/Aop` folder with following contents:
```php
<?php

namespace App\Aop;

use App\Aop\Aspects\DiscountAspect;
use Okapi\Aop\AopKernel;

class MyKernel extends AopKernel
{
    // Define a list of your custom aspects
    protected array $aspects = [
        DiscountAspect::class,
    ];   
}
```
3. Create your advices in the `app/Aop/Aspects` folder, e.g. `DiscountAspect.php`:
```php
// Discount Aspect

<?php

namespace App\Aop\Aspects;

use Okapi\Aop\Attributes\Aspect;
use Okapi\Aop\Attributes\After;
use Okapi\Aop\Invocation\AfterMethodInvocation;

// Aspects must be annotated with the "Aspect" attribute
#[Aspect]
class DiscountAspect
{
    // Annotate the methods that you want to intercept with
    // "Before", "Around" or "After" attributes
    #[After(
        // Use named arguments
        // You can also use Wildcards (see Okapi/Wildcards package)
        class: Product::class . '|' . Order::class,
        method: 'get(Price|Total)',
    )]
    public function applyDiscount(AfterMethodInvocation $invocation): void
    {
        // Get the subject of the invocation
        // The subject is the object class that contains the method
        // that is being intercepted
        $subject = $invocation->getSubject();
        
        $productDiscount = 0.1;
        $orderDiscount   = 0.2;
        
        if ($subject instanceof Product) {
            // Get the result of the original method
            $oldPrice = $invocation->proceed();
            $newPrice = $oldPrice - ($oldPrice * $productDiscount);
            
            // Set the new result
            $invocation->setResult($newPrice);
        }
        
        if ($subject instanceof Order) {
            $oldTotal = $invocation->proceed();
            $newTotal = $oldTotal - ($oldTotal * $orderDiscount);
            
            $invocation->setResult($newTotal);
        }
    }
}
```

**Comment by inmanturbo** [comment]
But where to register or initialize the Kernel? If I add it to a service provider or `bootstrap/app.php` I just get an error:
```
  The singleton instance of App\Aop\Kernel has already been initialized.
``` 

```php
// Initialize the AOP Kernel
$kernel = App\Aop\Kernel::init();
```

Otherwise, if I do not add it, the kernel is just ignored and I get no errors and no applied advice

**Comment by inmanturbo** [comment]
I should say, I see it working now in the browser, with the kernel initialized in `bootstrap/app.php`, but I am only getting the error in the terminal, when trying to run tests.

**Comment by WalterWoshid** [comment]
You're right, I missed that, sorry.

`bootstrap/app.php` is a good location, best to place it is after the `include "../vendor/autoload.php"` statement of the application life cycle (Before the code you want to intercept).

If you receive the error only when you run the tests, make sure your code doesn't call `Kernel::init()` twice.

**Comment by inmanturbo** [comment]
Strangely, if I put it directly in `public/index.php`, right after `require __DIR__.'/../vendor/autoload.php';` it continues to work in the browser but doesn't cause any errors in the test. No code is intercepted in the tests either though. It could have something to do with how orchestra builds the application.

In any case, the code doesn't call `Kernel::init()` more than the one time: there are no calls to it during tests or the test setup.

Here are my chages to a fresh [jetstream](https://github.com/laravel/jetstream) project with `livewire` stack:

index.php:

```diff
/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| this application. We just need to utilize it! We'll simply require it
| into the script here so we don't need to manually load our classes.
|
*/

require __DIR__.'/../vendor/autoload.php';

+$aopKernel = App\Aop\Kernel::init();
```

app/Aop/Kernel.php:

```php
<?php

namespace App\Aop;

use App\JetstreamAspect;
use Okapi\Aop\AopKernel;

// Extend from the "AopKernel" class
class Kernel extends AopKernel
{
    // Define a list of aspects
    protected array $aspects = [
        JetstreamAspect::class,
    ];   
}
```

app/JetstreamAspect.php:

```php
<?php

namespace App;

use App\Actions\Fortify\CreateNewUser;
use Okapi\Aop\Attributes\Aspect;
use Okapi\Aop\Attributes\After;
use Okapi\Aop\Invocation\AfterMethodInvocation;

// Aspects must be annotated with the "Aspect" attribute
#[Aspect]
class JetstreamAspect
{
    // This method will be executed after the "create" method of the "App\Actions\Fortify\CreateNewUser" class
    #[After(
        class: CreateNewUser::class,
        method: 'create',
    )]
    public function afterCreate(AfterMethodInvocation $invocation)
    {
        // testing various intercepts here
       // register as new user in the browser to see this code run
       // I expect this to die and dump after this method is called during the RegistrationTest
        dd('executed after the "create" method of the "App\Actions\Fortify\CreateNewUser" class');
    }
}
```

**Comment by akelalix** [comment]
hi @inmanturbo 

have you successfully setup it on laravel application?

when I add the kernel::init on the bootstrap/app.php just before return the $app, it was working but got some error `Cannot declare class App\Aop\MyKernel, because the name is already in use` when I tried to run the `php artisan config:cache`

thank you

**Comment by inmanturbo** [comment]
This error is often from a mismatch from file name to class name. Is your file called 'Kernel.php' or 'MyKernel.php' ?

**Comment by akelalix** [comment]
> This error is often from a mismatch from file name to class name. Is your file called 'Kernel.php' or 'MyKernel.php' ?

my mistake.. thank you

**Comment by WalterWoshid** [comment]
Hi @inmanturbo, sorry for the late response, I will test it now with a fresh Laravel Jetstream installation.

**Comment by WalterWoshid** [comment]
@inmanturbo I have found the problem. `bootstrap/app.php` should be the file where you add your kernel, also it does seem like the test framework bootstraps the application multiple times. In that case you can add an `if` check to the `bootstrap/app.php` file like this:
```php
if (!\App\Aop\Kernel::isInitialized()) {
    \App\Aop\Kernel::init();
}
``` 

I will add an option in the future to ignore an already initialized kernel and make it the default behaviour!

**Comment by WalterWoshid** [comment]
Hi @akelalix,

you don't have to require the class
```php
$path = realpath(DIR.'/..') . '/app/Aop/MyKernel.php';
require($path);
```
because `bootstrap/app.php` will be executed right after `require __DIR__.'/../vendor/autoload.php';` and it should automatically autoload all your classes. 

In case PHP still doesn't know about your `MyKernel.php` file, try to run the `composer dump-autoload` command in your terminal.

**Comment by akelalix** [comment]
> ```
> ```
> if (!\App\Aop\Kernel::isInitialized()) {
>     \App\Aop\Kernel::init();
> }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> ```

Thank you @WalterWoshid . 
I-remove the require then use the suggested 

`if (!\App\Aop\MyKernel::isInitialized()) {
    \App\Aop\MyKernel::init();
}`

Thanks again

**Comment by WalterWoshid** [comment]
I have added the `$throwExceptionOnDoubleInitialization` option to the `CodeTransformerKernel` (which is extended by the `AopKernel`) and the default value is set to `false` which makes it ignore subsequent `init()` calls. By running `composer update` in your project, you should be able to use it without any changes and can also remove this code:
```php
if (!\App\Aop\Kernel::isInitialized()) {
    \App\Aop\Kernel::init();
}
```

**Comment by Cyrille37** [comment]
Hello

It works fine with php 8.2, laravel 10.18 and php-aop 1.2.3 :-)

With first lines of `bootstrap/app.php` as:
```
<?php

use App\Aop\Kernel as AopKernel;
AopKernel::init();
...
```
