### ISSUE TITLE
Advices does not work properly with variadic parameters

### ISSUE THREAD

**Issue by jakublabno** [okapi-web/php-aop#26]
Uncaught TypeError: Core\Annotations\AnnotationFinder__AopProxied::findInPath(): Argument #2 must be of type string, array given in /app/cache/aop/proxies/src/Annotations/AnnotationFinder.php:28

```
public function findInPath(string $annotation, string ...$paths)
```

execution:
```
findInPath('any, 'path1', 'path2');
```

**Comment by WalterWoshid** [comment]
Hello @jakublabno,

I have fixed this with `okapi-aop: 1.2.3` and also added a test case (https://github.com/okapi-web/php-aop/pull/27)
