### ISSUE TITLE
protected method is intercepted when wildcard used

### ISSUE THREAD

**Issue by Cyrille37** [okapi-web/php-aop#29]
Hello

At first, thanks a lot for this really nice work. Also thanks for taking over from the sleeping [goaop](https://github.com/goaop/framework).
But we're here about coding, isn't it :-P
So:

I use Php 8.2.7 and Laravel 10.18 - thanks for #25

This Aspect works fine (*I confess I was pleasantly surprised*):
```
#[Aspect]
class AuthAspect{
    #[After(
        class: 'App\Http\Controllers\*',
        method: '*',
    )]
    public function afterCall(AfterMethodInvocation $invocation)
    {
        Log::debug(__METHOD__);
    }
}
```

Expect **that is also "catch" protected methods** ...

The original class is like:
```
namespace App\Http\Controllers;
class DashboardController extends Controller
{
    public function index() { ... }

    protected function &fillData(): array
    {
        $data = [];
        return $data ;
    }
}
```

I got the error "Only variable references should be returned by reference" and the Laravel error catcher show me the code where the error occurred :
```
    public function &fillData(): array
    {
        $data = [];
        return $data ;
    }
```

As you can see, the **protected** method "fillData()" has become **public** ; And as it returns a reference the php-aop failed.

In "Limitations" documentation's section it's wrote "Internal "private" and "protected" methods cannot be intercepted".

Would you have any recommendations for a right code organization and Wildcard matching?

Thanks & cheers

**Comment by Cyrille37** [comment]
I would be nice that for "Implicit Aspects" private & protected methods are ignored.

**Comment by Cyrille37** [comment]
Forget this newbie's issue :-)

**Comment by WalterWoshid** [comment]
Hi @Cyrille37,

thanks for your kind words, I appreciate it :)

I see, that I should forget it now, but I want to clarify that by `internal` I meant built-in methods, like `Directory::close()`, maybe I should document it a little better in the `README.md`
