### ISSUE TITLE
Set the cacheDir

### ISSUE THREAD

**Issue by djschilling** [okapi-web/php-aop#57]
I would like to set the cacheDir but there seem to be no method to do that.

**Comment by WalterWoshid** [comment]
Hi @djschilling,

the options for doing that (and some more) are in the protected properties (and methods) of your AOP Kernel. In your case, it would be the `protected ?string $cacheDir` property :)

**Comment by WalterWoshid** [comment]
I will make sure to document that in the `README.md` file

**Comment by djschilling** [comment]
good to know, but my use case does sadly not work with this solution. I want something like this:

` protected ?string $cacheDir = sys_get_temp_dir() . '/ct-aop-cache/' . BUILD_VERSION;`

But i cannot call the function there

**Comment by WalterWoshid** [comment]
Hi @djschilling, I understand now. You can just override the `preInit` method, because the options are configured in there. It should look like this in your case:
```php
class MyKernel extends AopKernel
{
    ...

    protected function preInit(): void
    {
        $this->cacheDir = sys_get_temp_dir() . '/ct-aop-cache/' . BUILD_VERSION;

        parent::preInit();
    }
    
    ...
}
```

Let me know if that worked for you :)

**Comment by djschilling** [comment]
that worked, thx.
