### ISSUE TITLE
Advices cannot be registered directly on classes

### ISSUE THREAD

**Issue by jakublabno** [okapi-web/php-aop#7]
Declaring supported classes directly in aspect is not convenient at all, there should be a way to make aspect more generic and decision about applying advice should be made directly on class with attribute e.g. #[Payment]
```php
#[Aspect]
class PaymentProcessorAspect
{
    #[Before(
        class: PaymentProcessor::class,
        method: 'processPayment',
    )]
    public function checkPaymentAmount(BeforeMethodInvocation $invocation): void
    {
        $payment = $invocation->getArgument('amount');
        
        if ($payment < 0) {
            throw new InvalidArgumentException('Invalid payment amount');
        }
    }
```

**Comment by WalterWoshid** [comment]
See #8 for status

**Comment by WalterWoshid** [comment]
Hi @jakublabno,

I have implemented Method-Level Explicit Aspects, see https://github.com/okapi-web/php-aop/issues/8 for an example and version `1.1.0` for the new feature. I have added tests and I will add Class-Level Explicit Aspects in the next update :)

**Comment by WalterWoshid** [comment]
I have also implemented Class-Level Explicit Aspects: https://github.com/okapi-web/php-aop/pull/20, check out version `1.2.0` and `README.md` for more information
